import type { AgentDefinition } from '@/types/agent';
import type { Waypoint } from '@/types/scene';

export const OFFICE_PALETTE = {
  sceneBackground: '#1f362c',
  outline: '#5c6874',
  tileSage: '#b2beb5',
  tileGray: '#c5cbc8',
  tileGrout: '#a8b0b8',
  wall: '#eceff2',
  wallMarble: '#e2e6ea',
  wallStripe: '#d4dae0',
  wallAccent: '#d8dee4',
  wood: '#c4a882',
  woodLight: '#e8d9bc',
  woodDark: '#8f7354',
  woodTable: '#5c4838',
  deskTop: '#e4d2b4',
  deskLeg: '#f6f8fa',
  monitor: '#343c46',
  monitorGlow: '#9ab8d8',
  sage: '#87a685',
  sageDark: '#6a8568',
  terracotta: '#c86a48',
  terracottaLight: '#e2725b',
  plant: '#5c9a6c',
  plantDark: '#3f704c',
  plantPot: '#b89068',
  potCeramic: '#f2f4f6',
  whiteboard: '#fafcfd',
  rug: '#a0907c',
  rugWeave: '#8f7f6c',
  metal: '#a8b2bc',
  espresso: '#2e2e34',
  stringLight: '#ffedb8',
  underGlow: '#ffdba0',
  chairMesh: '#383e46',
  chairTan: '#bea078',
  chairCream: '#e8dece',
  chairWhite: '#f4f2ee',
  chairYellow: '#e5c76a',
  olive: '#7a8c68',
  stoolGray: '#c8ccd0',
  chairForest: '#4a6b52',
  platformWood: '#a67b5b',
  zoneMatSage: '#9aab9e',
  matTransition: '#b0a494',
  glass: '#b8dce4',
  mug: '#f0f2f4',
  notebook: '#faf8f4',
  selectionGlow: '#ffe9a8',
} as const;

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  {
    id: 'cursor-agent',
    name: 'Cursor',
    modelId: 'gpt-4o-mini',
    logoUrl: '/logos/cursor.svg',
    avatarColor: '#6eb5ff',
    accentColor: '#4a9eff',
    systemPrompt: 'You are Cursor, a helpful coding assistant in a creative office.',
    spawnPosition: [0.5, 0, 1.2],
  },
  {
    id: 'research-agent',
    name: 'Research',
    modelId: 'gpt-4o',
    logoUrl: '/logos/research.svg',
    avatarColor: '#b88cff',
    accentColor: '#9a6bff',
    systemPrompt: 'You are a research specialist who summarizes and explores ideas clearly.',
    spawnPosition: [-3.8, 0, 0.4],
  },
  {
    id: 'design-agent',
    name: 'Design',
    modelId: 'claude-3-5-sonnet',
    logoUrl: '/logos/design.svg',
    avatarColor: '#ff9a7a',
    accentColor: '#ff7b55',
    systemPrompt: 'You are a design-minded assistant focused on UX and visual coherence.',
    spawnPosition: [-0.5, 0, -2.8],
  },
  {
    id: 'ops-agent',
    name: 'Ops',
    modelId: 'gpt-4o-mini',
    logoUrl: '/logos/ops.svg',
    avatarColor: '#7dd87d',
    accentColor: '#5bc45b',
    systemPrompt: 'You are an operations assistant who helps with workflows and reliability.',
    spawnPosition: [4.5, 0, 1.8],
  },
];

export const OFFICE_WAYPOINTS: Waypoint[] = [
  { id: 'wp-hub-1', position: [0.5, 0, 1.3] },
  { id: 'wp-hub-2', position: [-0.4, 0, 0.9] },
  { id: 'wp-meeting', position: [-3.6, 0, 0.6] },
  { id: 'wp-meeting-2', position: [-3, 0, -0.5] },
  { id: 'wp-lounge', position: [0.2, 0, -2.6] },
  { id: 'wp-lounge-2', position: [-1.2, 0, -3.2] },
  { id: 'wp-private', position: [4.8, 0, 1.4] },
  { id: 'wp-private-2', position: [4, 0, 2.6] },
  { id: 'wp-center', position: [1, 0, 1.2] },
  { id: 'wp-wing', position: [3.6, 0, 0.1] },
];

export const SCENE_CONFIG = {
  bounds: { minX: -6.5, maxX: 7, minZ: -5.5, maxZ: 5 },
  walkSpeed: 1.05,
  idlePauseMin: 2,
  idlePauseMax: 5,
} as const;
