import { getZoneWaypoints } from '@/config/agentZones.config';
import type { OfficeZoneId } from '@/config/officeZones';
import type { AgentDefinition } from '@/types/agent';

export const OFFICE_PALETTE = {
  sceneBackground: '#1a382e',
  outline: '#5c6874',
  tileSage: '#b2beb5',
  tileGray: '#c8cec9',
  tileGrout: '#a8b0a8',
  wall: '#eceff2',
  wallMarble: '#e4e8ec',
  wallStripe: '#d6dce2',
  wallAccent: '#dde2e8',
  wood: '#c4a882',
  woodLight: '#e8d9bc',
  woodDark: '#8f7354',
  woodTable: '#6b5340',
  deskTop: '#e6d4b6',
  deskLeg: '#f8fafc',
  monitor: '#2e343c',
  monitorGlow: '#9ab8d8',
  sage: '#87a685',
  sageDark: '#5a7358',
  terracotta: '#c86a48',
  terracottaLight: '#e2725b',
  plant: '#5c9a6c',
  plantDark: '#3d6848',
  plantPot: '#b89068',
  potCeramic: '#f4f6f8',
  whiteboard: '#fafcfd',
  rug: '#a89078',
  rugWeave: '#9a8570',
  metal: '#a8b2bc',
  espresso: '#2a2a30',
  stringLight: '#ffedb8',
  underGlow: '#ffdba0',
  chairMesh: '#383e46',
  chairTan: '#bea078',
  chairCream: '#e8dece',
  chairWhite: '#f4f2ee',
  chairYellow: '#e5c76a',
  olive: '#7a8c68',
  stoolGray: '#c8ccd0',
  chairForest: '#4a6b52',
  platformWood: '#a67b5b',
  zoneMatSage: '#9aab9e',
  matTransition: '#b0a494',
  glass: '#b8dce4',
  mug: '#f0f2f4',
  notebook: '#faf8f4',
  selectionGlow: '#ffe9a8',
  fog: '#2a4538',
} as const;

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  {
    id: 'cursor-agent',
    name: 'Cursor',
    role: 'Code',
    modelId: 'gpt-4o-mini',
    logoUrl: '/logos/cursor.svg',
    avatarColor: '#6eb5ff',
    accentColor: '#4a9eff',
    homeZone: 'center-desk',
    systemPrompt: 'You are Cursor, a helpful coding assistant in a creative office.',
  },
  {
    id: 'research-agent',
    name: 'Research',
    role: 'Research',
    modelId: 'gpt-4o',
    logoUrl: '/logos/research.svg',
    avatarColor: '#b88cff',
    accentColor: '#9a6bff',
    homeZone: 'living',
    systemPrompt: 'You are a research specialist who summarizes and explores ideas clearly.',
  },
  {
    id: 'design-agent',
    name: 'Design',
    role: 'Design',
    modelId: 'claude-3-5-sonnet',
    logoUrl: '/logos/design.svg',
    avatarColor: '#ff9a7a',
    accentColor: '#ff7b55',
    homeZone: 'cafeteria',
    systemPrompt: 'You are a design-minded assistant focused on UX and visual coherence.',
  },
  {
    id: 'ops-agent',
    name: 'Ops',
    role: 'Ops',
    modelId: 'gpt-4o-mini',
    logoUrl: '/logos/ops.svg',
    avatarColor: '#7dd87d',
    accentColor: '#5bc45b',
    homeZone: 'wall-desks',
    wallDeskSlot: 0,
    systemPrompt: 'You are an operations assistant who helps with workflows and reliability.',
  },
  {
    id: 'review-agent',
    name: 'Review',
    role: 'QA',
    modelId: 'gpt-4o',
    logoUrl: '/logos/review.svg',
    avatarColor: '#f0c674',
    accentColor: '#e5b84a',
    homeZone: 'wall-desks',
    wallDeskSlot: 1,
    systemPrompt: 'You are a QA reviewer who checks quality, edge cases, and test coverage.',
  },
  {
    id: 'data-agent',
    name: 'Data',
    role: 'Analytics',
    modelId: 'claude-3-5-sonnet',
    logoUrl: '/logos/data.svg',
    avatarColor: '#5ec4d4',
    accentColor: '#3aa8bc',
    homeZone: 'wall-desks',
    wallDeskSlot: 2,
    systemPrompt: 'You are a data analyst who interprets metrics and surfaces insights clearly.',
  },
];

export function getAgentsByZone(zoneId: OfficeZoneId): AgentDefinition[] {
  if (zoneId === 'all') return AGENT_DEFINITIONS;
  return AGENT_DEFINITIONS.filter((agent) => agent.homeZone === zoneId);
}

export const OFFICE_WAYPOINTS = getZoneWaypoints('center-desk');

export const SCENE_CONFIG = {
  bounds: { minX: -6.5, maxX: 7, minZ: -5.5, maxZ: 5 },
  walkSpeed: 1.05,
  idlePauseMin: 2,
  idlePauseMax: 5,
  coffeeBreakChance: 0.24,
  coffeeDurationMin: 4,
  coffeeDurationMax: 9,
} as const;
