import { hubPerimeterPosition } from '@/config/officeObstacles';
import { PRIVATE_DESK_CENTER, PRIVATE_DESK_POSITIONS, PRIVATE_DESK_X } from '@/components/scene/furniture/deskConstants';
import type { AgentDefinition } from '@/types/agent';
import type { Waypoint } from '@/types/scene';

export const OFFICE_PALETTE = {
  sceneBackground: '#1a382e',
  outline: '#5c6874',
  tileSage: '#b2beb5',
  tileGray: '#c8cec9',
  tileGrout: '#a8b0a8',
  wall: '#eceff2',
  wallMarble: '#e4e8ec',
  wallStripe: '#d6dce2',
  wallAccent: '#dde2e8',
  wood: '#c4a882',
  woodLight: '#e8d9bc',
  woodDark: '#8f7354',
  woodTable: '#6b5340',
  deskTop: '#e6d4b6',
  deskLeg: '#f8fafc',
  monitor: '#2e343c',
  monitorGlow: '#9ab8d8',
  sage: '#87a685',
  sageDark: '#5a7358',
  terracotta: '#c86a48',
  terracottaLight: '#e2725b',
  plant: '#5c9a6c',
  plantDark: '#3d6848',
  plantPot: '#b89068',
  potCeramic: '#f4f6f8',
  whiteboard: '#fafcfd',
  rug: '#a89078',
  rugWeave: '#9a8570',
  metal: '#a8b2bc',
  espresso: '#2a2a30',
  stringLight: '#ffedb8',
  underGlow: '#ffdba0',
  chairMesh: '#383e46',
  chairTan: '#bea078',
  chairCream: '#e8dece',
  chairWhite: '#f4f2ee',
  chairYellow: '#e5c76a',
  olive: '#7a8c68',
  stoolGray: '#c8ccd0',
  chairForest: '#4a6b52',
  platformWood: '#a67b5b',
  zoneMatSage: '#9aab9e',
  matTransition: '#b0a494',
  glass: '#b8dce4',
  mug: '#f0f2f4',
  notebook: '#faf8f4',
  selectionGlow: '#ffe9a8',
  fog: '#2a4538',
} as const;

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  {
    id: 'cursor-agent',
    name: 'Cursor',
    modelId: 'gpt-4o-mini',
    logoUrl: '/logos/cursor.svg',
    avatarColor: '#6eb5ff',
    accentColor: '#4a9eff',
    systemPrompt: 'You are Cursor, a helpful coding assistant in a creative office.',
    spawnPosition: hubPerimeterPosition(-Math.PI / 2 + 0.35),
  },
  {
    id: 'research-agent',
    name: 'Research',
    modelId: 'gpt-4o',
    logoUrl: '/logos/research.svg',
    avatarColor: '#b88cff',
    accentColor: '#9a6bff',
    systemPrompt: 'You are a research specialist who summarizes and explores ideas clearly.',
    spawnPosition: [-3.75, 0, 0.9],
  },
  {
    id: 'design-agent',
    name: 'Design',
    modelId: 'claude-3-5-sonnet',
    logoUrl: '/logos/design.svg',
    avatarColor: '#ff9a7a',
    accentColor: '#ff7b55',
    systemPrompt: 'You are a design-minded assistant focused on UX and visual coherence.',
    spawnPosition: [1.2, 0, -2.54],
  },
  {
    id: 'ops-agent',
    name: 'Ops',
    modelId: 'gpt-4o-mini',
    logoUrl: '/logos/ops.svg',
    avatarColor: '#7dd87d',
    accentColor: '#5bc45b',
    systemPrompt: 'You are an operations assistant who helps with workflows and reliability.',
    spawnPosition: [2.9, 0, 1.05],
  },
];

export const OFFICE_WAYPOINTS: Waypoint[] = [
  { id: 'wp-hub-north', position: hubPerimeterPosition(-Math.PI / 2) },
  { id: 'wp-hub-east', position: hubPerimeterPosition(0) },
  { id: 'wp-hub-west', position: hubPerimeterPosition(Math.PI) },
  { id: 'wp-hub-south', position: hubPerimeterPosition(Math.PI / 2) },
  { id: 'wp-meeting', position: [-3.85, 0, 0.85] },
  { id: 'wp-meeting-rug', position: [-4.95, 0, -0.15] },
  { id: 'wp-corridor', position: [-0.8, 0, -0.4] },
  { id: 'wp-lounge-front', position: [1.0, 0, -2.5] },
  { id: 'wp-lounge-side', position: [-2.1, 0, -3.0] },
  { id: 'wp-private-path', position: [4.2, 0, PRIVATE_DESK_CENTER[2]] },
  { id: 'wp-private-near', position: [5.4, 0, PRIVATE_DESK_CENTER[2]] },
  { id: 'wp-private-desk-a', position: [PRIVATE_DESK_X - 0.5, 0, PRIVATE_DESK_POSITIONS[0][2]] },
  { id: 'wp-private-desk-b', position: [PRIVATE_DESK_X - 0.5, 0, PRIVATE_DESK_POSITIONS[1][2]] },
];

export const SCENE_CONFIG = {
  bounds: { minX: -6.5, maxX: 7, minZ: -5.5, maxZ: 5 },
  walkSpeed: 1.05,
  idlePauseMin: 2,
  idlePauseMax: 5,
} as const;
